In [12]:
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')

In [13]:
FULL_LOG ='log_hours.csv'
df = pd.read_csv(FULL_LOG,index_col=0)

In [14]:
time_format = '%A %d %b %y %Hh%M:%S'
df['t0'] = pd.to_datetime(df['debut'],format=time_format).dt.tz_localize('CET')
df['t1'] = pd.to_datetime(df['fin'],format=time_format).dt.tz_localize('CET')
df.loc[df['t0'].idxmax(),'t1'] = pd.Timestamp.now('CET')

In [15]:
df

,debut,fin,task,t0,t1
16,Tuesday 16 Apr 24 11h49:18,NaN,task_manager,2024-04-16 11:49:18+02:00,2024-04-16 13:14:43.045249+02:00
15,Tuesday 16 Apr 24 11h26:36,Tuesday 16 Apr 24 11h49:18,pause,2024-04-16 11:26:36+02:00,2024-04-16 11:49:18+02:00
14,Tuesday 16 Apr 24 09h04:41,Tuesday 16 Apr 24 11h26:36,task_manager,2024-04-16 09:04:41+02:00,2024-04-16 11:26:36+02:00
13,Tuesday 16 Apr 24 08h00:13,Tuesday 16 Apr 24 09h04:41,meeting_sudharsan,2024-04-16 08:00:13+02:00,2024-04-16 09:04:41+02:00
11,Monday 15 Apr 24 12h20:57,Monday 15 Apr 24 14h25:03,create_gitlab_repo_setup,2024-04-15 12:20:57+02:00,2024-04-15 14:25:03+02:00
10,Monday 15 Apr 24 11h09:24,Monday 15 Apr 24 12h20:57,meeting_jean_yves,2024-04-15 11:09:24+02:00,2024-04-15 12:20:57+02:00
9,Monday 15 Apr 24 10h59:08,Monday 15 Apr 24 11h09:24,create_gitlab_repo,2024-04-15 10:59:08+02:00,2024-04-15 11:09:24+02:00
8,Monday 15 Apr 24 10h33:55,Monday 15 Apr 24 10h59:08,pause,2024-04-15 10:33:55+02:00,2024-04-15 10:59:08+02:00
7,Monday 15 Apr 24 10h21:22,Monday 15 Apr 24 10h33:55,issue_smartsupervision_41_ping,2024-04-15 10:21:22+02:00,2024-04-15 10:33:55+02:00
6,Monday 15 Apr 24 09h44:10,Monday 15 Apr 24 10h21:22,work_planification,2024-04-15 09:44:10+02:00,2024-04-15 10:21:22+02:00
5,Friday 12 Apr 24 09h22:06,Friday 12 Apr 24 11h01:02,meeting_setup_review,2024-04-12 09:22:06+02:00,2024-04-12 11:01:02+02:00
4,Friday 12 Apr 24 08h33:39,Friday 12 Apr 24 09h22:06,pause,2024-04-12 08:33:39+02:00,2024-04-12 09:22:06+02:00
3,Friday 12 Apr 24 07h30:08,Friday 12 Apr 24 08h33:39,meeting_smartsupervision,2024-04-12 07:30:08+02:00,2024-04-12 08:33:39+02:00
2,Friday 12 Apr 24 07h17:34,Friday 12 Apr 24 07h30:08,issue_smartsupervision_41_ping,2024-04-12 07:17:34+02:00,2024-04-12 07:30:08+02:00
1,Friday 12 Apr 24 06h20:47,Friday 12 Apr 24 07h17:34,work_planification,2024-04-12 06:20:47+02:00,2024-04-12 07:17:34+02:00

In [16]:
df['total seconds'] = (df['t1'] - df['t0']).dt.total_seconds()

In [17]:
def format_time_elapsed(s):
    if s is np.nan:
        return np.nan
    m = round(s/60)
    h = m//60
    m = m%60
    return str(h)+'h'+str(m)
hours_minutes=df['total seconds'].dropna().apply(lambda x:format_time_elapsed(x))
hours_minutes.name='time elapsed'
df2=df.merge(hours_minutes,left_index=True,right_index=True,how='left')

## assign categories

In [18]:
df2['week'] = [k.week for k in df2['t0']]
df2['month'] = [k.month for k in df2['t0']]

import re
def assign_categorie(task):
    for l in ['issue_smartsupervision_','issue_setupmanagement_','meeting_']:
        if re.match('^'+l,task):
            return l[:-1]
    return task
df2['categorie'] = df2['task'].apply(lambda x:assign_categorie(x))
df2['date'] = df2['t0'].dt.date

## hours every day this week

In [19]:
df_week = df2[df2['week']==pd.Timestamp.now(tz='CET').week]
df_week_woPause = df_week[df_week['categorie']!='pause']
df_hours_week = df_week_woPause.groupby('date').agg({'total seconds':'sum'}).squeeze().apply(format_time_elapsed).iloc[::-1]
df_hours_week.index = pd.to_datetime(df_hours_week.index).strftime('%A %d %b %y')
df_hours_week

date
Tuesday 16 Apr 24    4h52
Monday 15 Apr 24     4h16
Name: total seconds, dtype: object

## total hours spent each week

In [20]:
df2[df2['categorie']!='pause'].groupby('week').agg({'total seconds':'sum'}).squeeze().apply(format_time_elapsed).iloc[::-1]

week
16     9h7
15    3h52
Name: total seconds, dtype: object

## nb of working days this month

In [21]:
df_month = df2[df2['month']==pd.Timestamp.now(tz='CET').month]
df_month_woPause = df_month[df_month['categorie']!='pause']
df_days_months = df_month_woPause.groupby('date').agg({'total seconds':'sum'}).squeeze()/3600
df_days_months
(df_days_months>4).sum()

2

## total hours spent on each categorie this month

In [22]:
df_month

,debut,fin,task,t0,t1,total seconds,time elapsed,week,month,categorie,date
16,Tuesday 16 Apr 24 11h49:18,NaN,task_manager,2024-04-16 11:49:18+02:00,2024-04-16 13:14:43.045249+02:00,5125.045249,1h25,16,4,task_manager,2024-04-16
15,Tuesday 16 Apr 24 11h26:36,Tuesday 16 Apr 24 11h49:18,pause,2024-04-16 11:26:36+02:00,2024-04-16 11:49:18+02:00,1362.000000,0h23,16,4,pause,2024-04-16
14,Tuesday 16 Apr 24 09h04:41,Tuesday 16 Apr 24 11h26:36,task_manager,2024-04-16 09:04:41+02:00,2024-04-16 11:26:36+02:00,8515.000000,2h22,16,4,task_manager,2024-04-16
13,Tuesday 16 Apr 24 08h00:13,Tuesday 16 Apr 24 09h04:41,meeting_sudharsan,2024-04-16 08:00:13+02:00,2024-04-16 09:04:41+02:00,3868.000000,1h4,16,4,meeting,2024-04-16
11,Monday 15 Apr 24 12h20:57,Monday 15 Apr 24 14h25:03,create_gitlab_repo_setup,2024-04-15 12:20:57+02:00,2024-04-15 14:25:03+02:00,7446.000000,2h4,16,4,create_gitlab_repo_setup,2024-04-15
10,Monday 15 Apr 24 11h09:24,Monday 15 Apr 24 12h20:57,meeting_jean_yves,2024-04-15 11:09:24+02:00,2024-04-15 12:20:57+02:00,4293.000000,1h12,16,4,meeting,2024-04-15
9,Monday 15 Apr 24 10h59:08,Monday 15 Apr 24 11h09:24,create_gitlab_repo,2024-04-15 10:59:08+02:00,2024-04-15 11:09:24+02:00,616.000000,0h10,16,4,create_gitlab_repo,2024-04-15
8,Monday 15 Apr 24 10h33:55,Monday 15 Apr 24 10h59:08,pause,2024-04-15 10:33:55+02:00,2024-04-15 10:59:08+02:00,1513.000000,0h25,16,4,pause,2024-04-15
7,Monday 15 Apr 24 10h21:22,Monday 15 Apr 24 10h33:55,issue_smartsupervision_41_ping,2024-04-15 10:21:22+02:00,2024-04-15 10:33:55+02:00,753.000000,0h13,16,4,issue_smartsupervision,2024-04-15
6,Monday 15 Apr 24 09h44:10,Monday 15 Apr 24 10h21:22,work_planification,2024-04-15 09:44:10+02:00,2024-04-15 10:21:22+02:00,2232.000000,0h37,16,4,work_planification,2024-04-15
5,Friday 12 Apr 24 09h22:06,Friday 12 Apr 24 11h01:02,meeting_setup_review,2024-04-12 09:22:06+02:00,2024-04-12 11:01:02+02:00,5936.000000,1h39,15,4,meeting,2024-04-12
4,Friday 12 Apr 24 08h33:39,Friday 12 Apr 24 09h22:06,pause,2024-04-12 08:33:39+02:00,2024-04-12 09:22:06+02:00,2907.000000,0h48,15,4,pause,2024-04-12
3,Friday 12 Apr 24 07h30:08,Friday 12 Apr 24 08h33:39,meeting_smartsupervision,2024-04-12 07:30:08+02:00,2024-04-12 08:33:39+02:00,3811.000000,1h4,15,4,meeting,2024-04-12
2,Friday 12 Apr 24 07h17:34,Friday 12 Apr 24 07h30:08,issue_smartsupervision_41_ping,2024-04-12 07:17:34+02:00,2024-04-12 07:30:08+02:00,754.000000,0h13,15,4,issue_smartsupervision,2024-04-12
1,Friday 12 Apr 24 06h20:47,Friday 12 Apr 24 07h17:34,work_planification,2024-04-12 06:20:47+02:00,2024-04-12 07:17:34+02:00,3407.000000,0h57,15,4,work_planification,2024-04-12

In [23]:
df_month.groupby('categorie').agg({'total seconds':'sum'}).squeeze().apply(format_time_elapsed).iloc[::-1]

categorie
work_planification          1h34
task_manager                3h47
pause                       1h36
meeting                     4h58
issue_smartsupervision      0h25
create_gitlab_repo_setup     2h4
create_gitlab_repo          0h10
Name: total seconds, dtype: object

## Hours worked per day in average

In [24]:
df_woPause = df2[df2['categorie']!='pause']
df_woPause = df_woPause.groupby('date').agg({'total seconds':'sum'}).squeeze()
df_woPause.agg(['max','min','mean','median']).apply(format_time_elapsed)

max       4h52
min       3h52
mean      4h20
median    4h16
Name: total seconds, dtype: object

In [25]:
df2

,debut,fin,task,t0,t1,total seconds,time elapsed,week,month,categorie,date
16,Tuesday 16 Apr 24 11h49:18,NaN,task_manager,2024-04-16 11:49:18+02:00,2024-04-16 13:14:43.045249+02:00,5125.045249,1h25,16,4,task_manager,2024-04-16
15,Tuesday 16 Apr 24 11h26:36,Tuesday 16 Apr 24 11h49:18,pause,2024-04-16 11:26:36+02:00,2024-04-16 11:49:18+02:00,1362.000000,0h23,16,4,pause,2024-04-16
14,Tuesday 16 Apr 24 09h04:41,Tuesday 16 Apr 24 11h26:36,task_manager,2024-04-16 09:04:41+02:00,2024-04-16 11:26:36+02:00,8515.000000,2h22,16,4,task_manager,2024-04-16
13,Tuesday 16 Apr 24 08h00:13,Tuesday 16 Apr 24 09h04:41,meeting_sudharsan,2024-04-16 08:00:13+02:00,2024-04-16 09:04:41+02:00,3868.000000,1h4,16,4,meeting,2024-04-16
11,Monday 15 Apr 24 12h20:57,Monday 15 Apr 24 14h25:03,create_gitlab_repo_setup,2024-04-15 12:20:57+02:00,2024-04-15 14:25:03+02:00,7446.000000,2h4,16,4,create_gitlab_repo_setup,2024-04-15
10,Monday 15 Apr 24 11h09:24,Monday 15 Apr 24 12h20:57,meeting_jean_yves,2024-04-15 11:09:24+02:00,2024-04-15 12:20:57+02:00,4293.000000,1h12,16,4,meeting,2024-04-15
9,Monday 15 Apr 24 10h59:08,Monday 15 Apr 24 11h09:24,create_gitlab_repo,2024-04-15 10:59:08+02:00,2024-04-15 11:09:24+02:00,616.000000,0h10,16,4,create_gitlab_repo,2024-04-15
8,Monday 15 Apr 24 10h33:55,Monday 15 Apr 24 10h59:08,pause,2024-04-15 10:33:55+02:00,2024-04-15 10:59:08+02:00,1513.000000,0h25,16,4,pause,2024-04-15
7,Monday 15 Apr 24 10h21:22,Monday 15 Apr 24 10h33:55,issue_smartsupervision_41_ping,2024-04-15 10:21:22+02:00,2024-04-15 10:33:55+02:00,753.000000,0h13,16,4,issue_smartsupervision,2024-04-15
6,Monday 15 Apr 24 09h44:10,Monday 15 Apr 24 10h21:22,work_planification,2024-04-15 09:44:10+02:00,2024-04-15 10:21:22+02:00,2232.000000,0h37,16,4,work_planification,2024-04-15
5,Friday 12 Apr 24 09h22:06,Friday 12 Apr 24 11h01:02,meeting_setup_review,2024-04-12 09:22:06+02:00,2024-04-12 11:01:02+02:00,5936.000000,1h39,15,4,meeting,2024-04-12
4,Friday 12 Apr 24 08h33:39,Friday 12 Apr 24 09h22:06,pause,2024-04-12 08:33:39+02:00,2024-04-12 09:22:06+02:00,2907.000000,0h48,15,4,pause,2024-04-12
3,Friday 12 Apr 24 07h30:08,Friday 12 Apr 24 08h33:39,meeting_smartsupervision,2024-04-12 07:30:08+02:00,2024-04-12 08:33:39+02:00,3811.000000,1h4,15,4,meeting,2024-04-12
2,Friday 12 Apr 24 07h17:34,Friday 12 Apr 24 07h30:08,issue_smartsupervision_41_ping,2024-04-12 07:17:34+02:00,2024-04-12 07:30:08+02:00,754.000000,0h13,15,4,issue_smartsupervision,2024-04-12
1,Friday 12 Apr 24 06h20:47,Friday 12 Apr 24 07h17:34,work_planification,2024-04-12 06:20:47+02:00,2024-04-12 07:17:34+02:00,3407.000000,0h57,15,4,work_planification,2024-04-12

In [28]:
df2[['debut','fin','time elapsed','task','categorie']].head()

,debut,fin,time elapsed,task,categorie
16,Tuesday 16 Apr 24 11h49:18,NaN,1h25,task_manager,task_manager
15,Tuesday 16 Apr 24 11h26:36,Tuesday 16 Apr 24 11h49:18,0h23,pause,pause
14,Tuesday 16 Apr 24 09h04:41,Tuesday 16 Apr 24 11h26:36,2h22,task_manager,task_manager
13,Tuesday 16 Apr 24 08h00:13,Tuesday 16 Apr 24 09h04:41,1h4,meeting_sudharsan,meeting
11,Monday 15 Apr 24 12h20:57,Monday 15 Apr 24 14h25:03,2h4,create_gitlab_repo_setup,create_gitlab_repo_setup

In [43]:
import pandas as pd

# Create a sample DataFrame
data = {'Column1': [1, 2, 3], 'Column2': ['A', 'B', 'C']}
df = df2.copy()

def format_pretty_table(df):
    # Define custom formatting for header
    def bold_header(col):
        return f"\033[1m{col}\033[0m"
    
    # Apply custom formatting to the header
    formatted_columns = [bold_header(col) for col in df.columns]
    
    # Display the header with column separation using bars
    header_str = ' | '.join(formatted_columns)
    
    # Display the data
    data_str = df.to_string(index=False, header=False, justify='left')
    
    # Concatenate the header and data
    result = f"{header_str}\n{data_str}"
    return result

debut | fin | task | t0 | t1 | total seconds | time elapsed | week | month | categorie | date
Tuesday 16 Apr 24 11h49:18                        NaN                   task_manager 2024-04-16 11:49:18+02:00 2024-04-16 13:14:43.045249+02:00 5125.045249 1h25 16 4             task_manager 2024-04-16
Tuesday 16 Apr 24 11h26:36 Tuesday 16 Apr 24 11h49:18                          pause 2024-04-16 11:26:36+02:00        2024-04-16 11:49:18+02:00 1362.000000 0h23 16 4                    pause 2024-04-16
Tuesday 16 Apr 24 09h04:41 Tuesday 16 Apr 24 11h26:36                   task_manager 2024-04-16 09:04:41+02:00        2024-04-16 11:26:36+02:00 8515.000000 2h22 16 4             task_manager 2024-04-16
Tuesday 16 Apr 24 08h00:13 Tuesday 16 Apr 24 09h04:41              meeting_sudharsan 2024-04-16 08:00:13+02:00        2024-04-16 09:04:41+02:00 3868.000000  1h4 16 4                  meeting 2024-04-16
 Monday 15 Apr 24 12h20:57  Monday 15 Apr 24 14h25:03       create_gitlab_repo_setup 2024-04-15 12:20:57+02:00        2024-04-15 14:25:03+02:00 7446.000000  2h4 16 4 create_gitlab_repo_setup 2024-04-15
 Monday 15 Apr 24 11h09:24  Monday 15 Apr 24 12h20:57              meeting_jean_yves 2024-04-15 11:09:24+02:00        2024-04-15 12:20:57+02:00 4293.000000 1h12 16 4                  meeting 2024-04-15
 Monday 15 Apr 24 10h59:08  Monday 15 Apr 24 11h09:24             create_gitlab_repo 2024-04-15 10:59:08+02:00        2024-04-15 11:09:24+02:00  616.000000 0h10 16 4       create_gitlab_repo 2024-04-15
 Monday 15 Apr 24 10h33:55  Monday 15 Apr 24 10h59:08                          pause 2024-04-15 10:33:55+02:00        2024-04-15 10:59:08+02:00 1513.000000 0h25 16 4                    pause 2024-04-15
 Monday 15 Apr 24 10h21:22  Monday 15 Apr 24 10h33:55 issue_smartsupervision_41_ping 2024-04-15 10:21:22+02:00        2024-04-15 10:33:55+02:00  753.000000 0h13 16 4   issue_smartsupervision 2024-04-15
 Monday 15 Apr 24 09h44:10  Monday 15 Apr 24 10h21:22             work_planification 2024-04-15 09:44:10+02:00        2024-04-15 10:21:22+02:00 2232.000000 0h37 16 4       work_planification 2024-04-15
 Friday 12 Apr 24 09h22:06  Friday 12 Apr 24 11h01:02           meeting_setup_review 2024-04-12 09:22:06+02:00        2024-04-12 11:01:02+02:00 5936.000000 1h39 15 4                  meeting 2024-04-12
 Friday 12 Apr 24 08h33:39  Friday 12 Apr 24 09h22:06                          pause 2024-04-12 08:33:39+02:00        2024-04-12 09:22:06+02:00 2907.000000 0h48 15 4                    pause 2024-04-12
 Friday 12 Apr 24 07h30:08  Friday 12 Apr 24 08h33:39       meeting_smartsupervision 2024-04-12 07:30:08+02:00        2024-04-12 08:33:39+02:00 3811.000000  1h4 15 4                  meeting 2024-04-12
 Friday 12 Apr 24 07h17:34  Friday 12 Apr 24 07h30:08 issue_smartsupervision_41_ping 2024-04-12 07:17:34+02:00        2024-04-12 07:30:08+02:00  754.000000 0h13 15 4   issue_smartsupervision 2024-04-12
 Friday 12 Apr 24 06h20:47  Friday 12 Apr 24 07h17:34             work_planification 2024-04-12 06:20:47+02:00        2024-04-12 07:17:34+02:00 3407.000000 0h57 15 4       work_planification 2024-04-12

In [44]:
from task_manager import *

In [45]:
get_hours_in_week().to_string()

'date\nWednesday 17 Apr 24    0h32\nTuesday 16 Apr 24      7h52\nMonday 15 Apr 24       4h16'

In [63]:
df_woPause = DF_LOG_HOURS[DF_LOG_HOURS['categorie']!='pause']
df_woPause = df_woPause.groupby('date').agg({'total seconds':'sum'}).squeeze()
df_woPause=df_woPause.agg(['max','min','mean','median']).apply(format_time_elapsed)
df_woPause['nb days'] = df_woPause.count()
df_woPause

max       7h52
min       0h32
mean       4h8
median     4h4
count        4
Name: total seconds, dtype: object